Stopping when finding an error.

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -8,10 +8,21 @@ do
    if [ -n "$test" -a "$file" != "./$test" ]; then 
       continue
    fi
+
    echo "running $file ..."
    if [ -n "$filter" ]; then
       phpunit --colors --debug --filter "$filter" $file
    else
       phpunit --colors --debug $file
+   fi
+
+   rst=$?
+   echo "test result: $rst errors"
+
+   if [ "$rst" != "0" ]; then
+      echo "*****************************************************************";
+      echo "Failed!"
+      echo "*****************************************************************";
+      exit 1
    fi
 done
